export const dotaSeed = [
    "Abaddon",
    "Alchemist",
    "Ancient Apparition",
    "Anti-Mage",
    "Arc Warden",
    "Axe",
    "Bane",
    "Batrider",
    "Beastmaster",
    "Bloodseeker",
    "Bounty Hunter",
    "Brewmaster",
    "Bristleback",
    "Broodmother",
    "Centaur Warrunner",
    "Chaos Knight",
    "Chen",
    "Clinkz",
    "Clockwerk",
    "Crystal Maiden",
    "Dark Seer",
    "Dark Willow",
    "Dawnbreaker",
    "Dazzle",
    "Death Prophet",
    "Disruptor",
    "Doom",
    "Dragon Knight",
    "Drow Ranger",
    "Earth Spirit",
    "Earthshaker",
    "Elder Titan",
    "Ember Spirit",
    "Enchantress",
    "Enigma",
    "Faceless Void",
    "Grimstroke",
    "Gyrocopter",
    "Hoodwink",
    "Huskar",
    "Invoker",
    "Io",
    "Jakiro",
    "Juggernaut",
    "Keeper of the Light",
    "Kunkka",
    "Legion Commander",
    "Leshrac",
    "Lich",
    "Lifestealer",
    "Lina",
    "Lion",
    "Lone Druid",
    "Luna",
    "Lycan",
    "Magnus",
    "Marci",
    "Mars",
    "Medusa",
    "Meepo",
    "Mirana",
    "Monkey King",
    "Morphling",
    "Muerta",
    "Naga Siren",
    "Nature's Prophet",
    "Necrophos",
    "Night Stalker",
    "Nyx Assassin",
    "Ogre Magi",
    "Omniknight",
    "Oracle",
    "Outworld Destroyer",
    "Pangolier",
    "Phantom Assassin",
    "Phantom Lancer",
    "Phoenix",
    "Primal Beast",
    "Puck",
    "Pudge",
    "Pugna",
    "Queen of Pain",
    "Razor",
    "Riki",
    "Rubick",
    "Sand King",
    "Shadow Demon",
    "Shadow Fiend",
    "Shadow Shaman",
    "Silencer",
    "Skywrath Mage",
    "Slardar",
    "Slark",
    "Snapfire",
    "Sniper",
    "Spectre",
    "Spirit Breaker",
    "Storm Spirit",
    "Sven",
    "Techies",
    "Templar Assassin",
    "Terrorblade",
    "Tidehunter",
    "Timbersaw",
    "Tinker",
    "Tiny",
    "Treant Protector",
    "Troll Warlord",
    "Tusk",
    "Underlord",
    "Undying",
    "Ursa",
    "Vengeful Spirit",
    "Venomancer",
    "Viper",
    "Visage",
    "Void Spirit",
    "Warlock",
    "Weaver",
    "Windranger",
    "Winter Wyvern",
    "Witch Doctor",
    "Wraith King",
    "Zeus",

    //

    "Observer Ward",
    "Clarity",
    "Sentry Ward",
    "Smoke of Deceit",
    "Enchanted Mango",
    "Dust of Appearance",
    "Tango",
    "Town Portal Scroll",
    "Bottle",
    "Iron Branch",

    "Blink Dagger",
    "Arcane Blink",
    "Overwhelming Blink",
    "Swift Blink",

    "Boots of Speed",
    "Power Treads",
    "Phase Boots",
    "Boots of Travel",
    "Tranquil Boots",
    "Arcane Boots",
    "Boots of Bearing",
    "Guardian Greaves",
    "Urn of Shadows",
    "Pipe of Insight",

    "Veil of Discord",
    "Force Staff",
    "Rod of Atos",
    "Aether Lens",
    "Eul's Scepter of Divinity",
    "Solar Crest",
    "Witch Blade",
    "Dagon",
    "Orchid Malevolence",
    "Aghanim's Scepter",
    "Octarine Core",
    "Refresher Orb",
    "Scythe of Vyse",
    "Gleipnir",
    "Wind Waker",

    "Vanguard",
    "Blade Mail",
    "Aeon Disk",
    "Soul Booster",
    "Eternal Shroud",
    "Crimson Guard",
    "Lotus Orb",
    "Black King Bar",
    "Bloodstone",
    "Hurricane Pike",
    "Manta Style",
    "Linken's Sphere",
    "Assault Cuirass",
    "Shiva's Guard",
    "Heart of Tarrasque",

    "Crystalys",
    "Armlet of Mordiggian",
    "Meteor Hammer",
    "Skull Basher",
    "Shadow Blade",
    "Desolator",
    "Battle Fury",
    "Nullifier",
    "Monkey King Bar",
    "Radiance",
    "Revenant's Brooch",
    "Khanda",
    "Daedalus",
    "Ethereal Blade",
    "Butterfly",
    "Silver Edge",
    "Divine Rapier",
    "Disperser",
    "Abyssal Blade",
    "Bloodthorn",

    "Dragon Lance",
    "Kaya",
    "Sange",
    "Yasha",
    "Phylactery",
    "Diffusal Blade",
    "Echo Sabre",
    "Mage Slayer",
    "Maelstrom",
    "Heaven's Halberd",
    "Yasha and Kaya",
    "Kaya and Sange",
    "Sange and Yasha",
    "Harpoon",
    "Satanic",
    "Eye of Skadi",
    "Mjollnir",

    "Aegis of the Immortal",
    "Cheese",
    "Refresher Shard",
    "Roshan's Banner",

    "Banana",
    "Animal Courier",
    "Tome of Knowledge",
    "Flying Courier",
    "Necronomicon",
    "Diffusal Blade",
];
