export const programmingSeed = [
    "Ассемблер",
    "Переменная",
    "Функция",
    "Условное выражение",
    "Цикл",
    "Массив",
    "Класс",
    "Объект",
    "Интерфейс",
    "Рекурсия",
    "Стек",
    "Куча / Heap",
    "Очередь",
    "SQL",
    "API",
    "GIT",
    "IDE",
    "Debugging",
    "Алгоритм",
    "Исключение",
    "База данных",
    "Индекс",
    "Асинхронная функция",
    "Поток",
    "REST",
    "MVC",
    "Хэширование",
    "Битовые операции",
    "Docker",
    "Рефакторинг",
    "Десериализация",
    "Регулярные выражения",
    "Сортировка",
    "ООП",
    "JSON",
    "Компиляция",
    "Интерпретация",
    "Тип данных",
    "Константа",
    "Псевдокод",
    "Итерация",
    "Метод",
    "Структура данных",
    "Модуль",
    "Виртуализация",
    "Криптография",
    "Эмуляция",
    "CDN",
    "Deadlock",
    "Unit Test",
    "Big O notation",
    "Многопоточность",
    "Атомарная операция",
    "ORM",
    "Инкапсуляция",
    "ASCII",
    "Бит",
    "Байт",
    "Вирус",
    "Драйвер",
    "Идентификатор",
    "Интернет",
    "Stack Overflow",
    "Битрикс",
    "WordPress",
    "Laravel",
    "Flatter",
    "JavaScript",
    "Dart",
    "PHP",
    "Python",
    "C++",
    "Java",
    "NPM",
    "Node",
    "Swiper",
    "Vue",
    "Go",
    "Бинарный код",
    "Vim",
    "VSCode",
    "http",
    "https",
    "ftp",
    "sftp",
    "html",
    "css",
    "scss",
    "Nuxt",
    "Svelte",
    "Курсор",
    "boolean",
    "integer",
    "float",
    "double",
    "string",
    "null",
    "Сервер",
    "Клиент",
    "Front-end",
    "Back-end",
    "Текстовый редактор",
    "switch",
    "return",
    "Админ",
    "Баг",
    "Код",
    "Консоль / Терминал",
    "Джун",
    "Мидл",
    "Сеньор",
    "Фреймворк",
    "Указатель",
    "Ссылка",
    "Код-ревью",
    "Merge",
    "Commit",
    "Адаптив",
    "Сallback",
    "DOM",
    "header",
    "footer",
    "Lorem ipsum",
    "Figma",
    "Postman",
    "CRUD",
    "XML",
    "Cookies",
    "Хостинг",
    "Open Server",
    "Apache",
    "Nginx",
    "HeidiSQL",
    "Vite",
    "Webpack",
    "Tailwind",
    "Bootstrap",
    "Redux",
    "nvm",
    "Firebase",
    "TypeScript",
    "Gulp",
    "Prettier",
    "Axios",
];
